# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='text',
        ),
        migrations.AddField(
            model_name='booking',
            name='city_in',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='city_out',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='country_in',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='country_out',
            field=models.TextField(default=''),
        ),
    ]
