# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_countries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countries',
            name='country',
        ),
        migrations.AddField(
            model_name='countries',
            name='country_code',
            field=models.CharField(default=b'', max_length=2),
        ),
        migrations.AddField(
            model_name='countries',
            name='name',
            field=models.CharField(default=b'', max_length=64),
        ),
        migrations.AlterModelTable(
            name='countries',
            table='country',
        ),
    ]
