# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_delete_countries'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Country')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='region_in',
            field=models.CharField(default=b'', max_length=30),
        ),
        migrations.AddField(
            model_name='booking',
            name='region_out',
            field=models.CharField(default=b'', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='city_in',
            field=models.CharField(default=b'', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='city_out',
            field=models.CharField(default=b'', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='country_in',
            field=models.CharField(default=b'', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='country_out',
            field=models.CharField(default=b'', max_length=30),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.State'),
        ),
    ]
