# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_auto_20160112_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_in',
            field=models.DateField(default=b''),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_out',
            field=models.DateField(default=b''),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(default=b'', max_length=254),
        ),
    ]
